### ISSUE TITLE
2022-11

### ISSUE THREAD

**Issue by snaag** [snaag/todo3#1]
### 11/12 ~ 11/13

**Comment by snaag** [comment]
- 11/12 토
   - 글 읽고 정리
      - [x] Spring boot 글 읽기 https://melonicedlatte.com/2021/07/11/174700.html
      - [x] 정리 https://github.com/snaag/TIL/issues/10#issuecomment-1312536915
   - 강의 듣고 정리하기
      - [ ] 스프링 강의 > 프로젝트 환경설정 다 듣기 -> ~프로젝트 생성 
      - [x] 정리하기 https://github.com/snaag/TIL/issues/10#issuecomment-1312536915

**Comment by snaag** [comment]
- 11/13 일
   - 강의 듣고 정리하기
      - [x] 스프링 강의 > 프로젝트 환경설정 다 듣고 정리하기 https://github.com/snaag/TIL/issues/11#issuecomment-1312768428 https://github.com/snaag/TIL/issues/11#issuecomment-1312771703
      - [ ] 스프링 강의 > 스프링 웹 개발 기초 다 듣고 정리하기 -> 2개 듣고 하나 남음 https://github.com/snaag/TIL/issues/11#issuecomment-1312807504 https://github.com/snaag/TIL/issues/11#issuecomment-1312807667

**Comment by snaag** [comment]
### 11/14 ~ 11/15
- 11/16 ~ 11/24 싱가포르

**Comment by snaag** [comment]
- 11/14 월
   - 강의 듣고 정리하기
      - [x] 스프링 강의 > 스프링 웹 개발 기초 다 듣고 정리하기 https://github.com/snaag/TIL/issues/12#issuecomment-1314037405 https://github.com/snaag/TIL/issues/12#issuecomment-1314041220
      - [x] 스프링 강의 > 회원 관리 예제 - 백엔드 개발 2강 듣고 정리하기 https://github.com/snaag/TIL/issues/12#issuecomment-1314110144 https://github.com/snaag/TIL/issues/12#issuecomment-1314120188

**Comment by snaag** [comment]
- 11/15 화
   - 강의 듣고 정리하기
      - [x] 스프링 강의 > 회원 관리 예제 - 백엔드 개발 - 회원 레포지토리 테스트 케이스 듣고 정리하기 https://github.com/snaag/TIL/issues/13#issuecomment-1315612941
      - [ ] 스프링 강의 > 회원 관리 예제 - 백엔드 개발 - 회원 서비스 개발 듣고 정리하기
      - [ ] 스프링 강의 > 회원 관리 예제 - 백엔드 개발 - 회원 서비스 테스트 듣고 정리하기

**Comment by snaag** [comment]
### 여행
- 11/16 ~ 11/24

**Comment by snaag** [comment]
### 11/25 ~ 11/27

**Comment by snaag** [comment]
- 11/25 금
   - [x] 스프링 강의 > 회원 관리 예제 - 백엔드 개발 - 회원 서비스 개발 듣고 정리하기 https://github.com/snaag/TIL/issues/14#issuecomment-1327766342
   - [x] 스프링 강의 > 회원 관리 예제 - 백엔드 개발 - 회원 서비스 테스트 듣고 정리하기 (상동)
   - [ ] 배운거 바탕으로 게시판 만들어보기

**Comment by snaag** [comment]
- 11/26 토
   - [x] 배운거 바탕으로 게시판 만들어보기 (1) https://github.com/snaag/TIL/issues/15
      - Controller, Domain, Repository, 그리고 Repository Test code 작성

**Comment by snaag** [comment]
- 11/27 일
   - [x] 배운거 바탕으로 게시판 만들어보기 (2) https://github.com/snaag/TIL/issues/16
      - Service, Service Test code 작성
   - [x] Java Optional 이해하고 정리하기 https://github.com/snaag/TIL/issues/16#issuecomment-1328217777
