### ISSUE TITLE
2022-12

### ISSUE THREAD

**Issue by snaag** [snaag/todo3#2]
### 11/28 ~ 12/4

**Comment by snaag** [comment]
- 11/28 월
   - [ ] 스프링 강의 > 스프링 빈과 의존관계 - 컴포넌트 스캔과 자동 의존관계 설정 듣고 정리
   - [ ] 스프링 강의 > 스프링 빈과 의존관계 - 자바 코드로 직접 스프링 빈 등록하기 듣고 정리
   - [ ] Spring session 글 읽고 정리하기 https://thecodinglog.github.io/spring-session/2020/08/07/filter-chain.html

**Comment by snaag** [comment]
- 12/3 토
   - [x] 스프링 강의 > 스프링 빈과 의존관계 - 컴포넌트 스캔과 자동 의존관계 설정 듣고 정리 https://github.com/snaag/TIL/issues/17#issuecomment-1336125798
   - [x] 스프링 강의 > 스프링 빈과 의존관계 - 자바 코드로 직접 스프링 빈 등록하기 듣고 정리 https://github.com/snaag/TIL/issues/17#issuecomment-1336140671
   - [x] 스프링 강의 > 회원 관리 예제 - 웹 MVC 개발 - 회원 웹 기능 - 홈 화면 추가
   - [x] 스프링 강의 > 회원 관리 예제 - 웹 MVC 개발 - 회원 웹 기능 - 등록
   - [x] 스프링 강의 > 회원 관리 예제 - 웹 MVC 개발 - 회원 웹 기능 - 조회
   - [x] 지난번 혼자하는 실습 이어서 배운데까지 적용 해보기 https://github.com/snaag/TIL/issues/17#issuecomment-1336192952

**Comment by snaag** [comment]
- 12/4 일
   - [ ] Spring session 글 읽고 정리하기 https://thecodinglog.github.io/spring-session/2020/08/07/filter-chain.html

**Comment by snaag** [comment]
### 12/5 ~ 12/11

**Comment by snaag** [comment]
- 12/5 월
   - [x] 스프링 강의 > 스프링 DB 접근 기술 - H2 데이터베이스 설치 https://github.com/snaag/TIL/issues/18#issuecomment-1337619365
   - [x] 스프링 강의 > 스프링 DB 접근 기술 - 순수 JDBC https://github.com/snaag/TIL/issues/18#issuecomment-1337620982

**Comment by snaag** [comment]
- 12/6 화
   - [x] 스프링 강의 > 스프링 DB 접근 기술 - 스프링 통합 테스트 https://github.com/snaag/TIL/issues/19#issuecomment-1338804967
   - [x] 스프링 강의 > 스프링 DB 접근 기술 - 스프링 JdbcTemplate https://github.com/snaag/TIL/issues/19#issuecomment-1339729428

**Comment by snaag** [comment]
- 12/7 수
   - [x] Spring Session 읽기
      - https://thecodinglog.github.io/spring-session/2020/08/07/filter-chain.html https://jerry92k.tistory.com/25
      - https://jerry92k.tistory.com/25
      - https://recordsoflife.tistory.com/382
      - https://engkimbs.tistory.com/696
      - https://develop-writing.tistory.com/m/87
   - [x] 배운데까지 실습 (H2 DB 연결, 순수 JDBC 로 구현, JdbcTemplate 으로 구현) https://github.com/snaag/TIL/issues/20#issue-1482101842

**Comment by snaag** [comment]
- 12/8 목
   - [x] 실습2 배운데까지 적용 (todo list), JDBC 로 하기 (1) https://github.com/snaag/study-spring02-todolist https://github.com/snaag/TIL/issues/21#issuecomment-1343281563
   - [x] http 정리 https://github.com/snaag/TIL/issues/21#issuecomment-1342693642

**Comment by snaag** [comment]
- 12/9 금
   - [x] 실습2 배운데까지 적용 (todo list), JDBC 로 하기 (2) [레포](https://github.com/snaag/study-spring02-todolist) https://github.com/snaag/TIL/issues/22#issuecomment-1344763011
   - [x] JDBC 간단 파악 https://github.com/snaag/TIL/issues/22#issuecomment-1344755394
   - [ ] socket, http 차이 정리

**Comment by snaag** [comment]
- 12/10 토
   - [x] 실습2 배운데까지 적용 (todo list), JDBC 로 하기 (3) [Repo](https://github.com/snaag/study-spring02-todolist) https://github.com/snaag/TIL/issues/23#issuecomment-1345519086
   - [x] Spring 에서 JDBC 사용해서 쿼리 날리는 내용 파악 및 정리 https://github.com/snaag/TIL/issues/23#issuecomment-1345242588
   - [ ] 스프링 강의 > 스프링 DB 접근 기술 - JPA 듣고 정리
   - [ ] 스프링 강의 > 스프링 DB 접근 기술 - 스프링 데이터 JPA 듣고 정리

**Comment by snaag** [comment]
### 12/12 ~ 12/18

**Comment by snaag** [comment]
### 12/12 ~ 12/18
- 12/15 (목) -> 전체 회식
- 12/17 (토) -> 연말 모임

**Comment by snaag** [comment]
- 12/12 월
   - [ ] 실습2 에서 작성한 JDBC 코드와 강의에서 봤던 JDBC 코드 비교해서 리팩토링 하기
   - [ ] 실습2 코드에 쿼리 날리는 부분 JDBCTemplate 으로 작성하기
   - [x] Spring, Redis Cluster /w Jedis https://github.com/snaag/TIL/issues/24#issuecomment-1346838644

**Comment by snaag** [comment]
- 12/13 화
   - [x] 실습2 에서 작성한 JDBC 코드와 강의에서 봤던 JDBC 코드 비교해서 리팩토링 하기 https://github.com/snaag/TIL/issues/25
   - [x] 실습2 코드에 쿼리 날리는 부분 JDBCTemplate 으로 작성하기 (1) (링크는 상동)

**Comment by snaag** [comment]
- 12/14 수
   - [x] 실습2 코드에 쿼리 날리는 부분 JDBCTemplate 으로 작성하기 (2) https://github.com/snaag/TIL/issues/26
   - [x] 실습2 UI 붙이기 (링크는 상동)

**Comment by snaag** [comment]
- 12/15 목
   - [ ] 스프링 강의 > 스프링 DB 접근 기술 - JPA 듣고 정리
   - [ ] 스프링 강의 > 스프링 DB 접근 기술 - 스프링 데이터 JPA 듣고 정리

**Comment by snaag** [comment]
- 12/16 금
   - [x] 스프링 강의 > 스프링 DB 접근 기술 - JPA 듣고 정리

**Comment by snaag** [comment]
- 12/17 토
   - [x] 스프링 강의 > 스프링 DB 접근 기술 - 스프링 데이터 JPA 듣고 정리

**Comment by snaag** [comment]
### ...

**Comment by snaag** [comment]
### 12/19 ~ 12/25
- 12/21 (수) -> 동호회 송년회
- 12/23 (금) -> 송년회
- 12/25 (일) -> 크리스마스

**Comment by snaag** [comment]
- 12/19 월
   - [x] nginx 로 reverse proxy 만들기 https://github.com/snaag/TIL/issues/29

**Comment by snaag** [comment]
- 12/20 화
   - [x] 스프링 입문강의 > AOP - AOP 가 필요한 상황 듣고 정리 https://github.com/snaag/TIL/issues/30#issuecomment-1359886546
   - [x] 스프링 입문강의 > AOP - AOP 적용 듣고 정리 https://github.com/snaag/TIL/issues/30#issuecomment-1359913858

**Comment by snaag** [comment]
- 12/21 수
   - [x] 개인 PJT (1)

**Comment by snaag** [comment]
- 12/22 목
   - [x] 개인 PJT (2) _ webpack

**Comment by snaag** [comment]
### 12/26 ~ 23/1/1 ☀️

**Comment by snaag** [comment]
- 12/26
   - [x] spring project (1) https://github.com/snaag/TIL/issues/33

**Comment by snaag** [comment]
- 12/27 화
   - [ ] spring project (2) _ mongo db, nginx 
   - [ ] java 공부 (강의 듣기)

**Comment by snaag** [comment]
- 12/28 수
   - [x] 책 친절한 SQL 튜닝 읽고 이해하고, 이해한 내용대로 정리 https://github.com/snaag/TIL/issues/34
