### ISSUE TITLE
2023-01

### ISSUE THREAD

**Issue by snaag** [snaag/todo3#3]
### ✅✅✅

**Comment by snaag** [comment]
### 1/9 ~ 1/15
- 1/10 (화) -> 모임

#### TODO
- [ ] NGINX 쿡북 Chapter 1 학습
- [ ] 스프링 강의 > 스프링 핵심 원리 이해1 - 예제 만들기 까지 완강하고 정리

**Comment by snaag** [comment]
- 1/10 화
   - [x] 스프링 강의 > 객체 지향 설계와 스프링 > 이야기 - 자바 진영의 추운 겨울과 스프링 탄생 듣고 정리 https://github.com/snaag/TIL/issues/38
   - [x] JavaBean 디깅 (상동)

**Comment by snaag** [comment]
- 1/11 수
   - [x] 스프링 강의 > 스프링이란? 듣고 정리 https://github.com/snaag/TIL/issues/39
   - [ ] 스프링 강의 > 좋은 객체지향 프로그래밍이란? 듣고 정리

**Comment by snaag** [comment]
- 1/12 목
  - [ ] 스프링 강의 > 좋은 객체지향 프로그래밍이란? 듣고 정리
  - [ ] 스프링 강의 > 좋은 객체지향 설계의 5가지 원칙 (SOLID) 듣고 정리
  - [ ] 스프링 강의 > 객체 지향 설계와 스프링 듣고 정리
  - [x] Kotlin 기본 문법 학습 (1)

**Comment by snaag** [comment]
- 1/13 금
  - [ ] Kotlin 기본 문법 학습 (2) - class
  - [ ] Kotlin 으로 프로그래머스 lv 1 문제 풀기
  - [ ] 스프링 강의 > 좋은 객체지향 프로그래밍이란? 듣고 정리

**Comment by snaag** [comment]
### 1/16 ~ 1/22
- 1/17 (화) -> 모임

**Comment by snaag** [comment]
### 1/18 (수)
- [ ] React 복습 (실습)
